### ISSUE TITLE
document units of various output

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#124]
It would be helpful if units for all input output files were documented. Things in `PREFIX.out` mostly (always?) are, but I've been assuming that the eigenvalues file is in Ha, but it would be nice if that were written someplace (either in the file or in the docs, or both).

**Comment by xuqimen** [comment]
Thanks for your feedback! The units of all the input options are documented in the [manual](https://github.com/SPARC-X/SPARC/blob/master/doc/Manual.pdf). And we usually mention the output units in the corresponding output files. But there might be some variables that fall through the net, such as the eigenvalues in the `.eigen` files you mentioned (which are in `Ha`). We'll fix that soon. Please let us know if you find any other output variables without units, we'll try to fix them.

**Comment by bernstei** [comment]
Thanks - if I find anything else I'll let you know. 

I guess one quantity that would definitely be helpful is the normalization of the density files. Do they sum to 1?  Integrate to 1? To total number of electrons (in each spin channel or total)?

**Comment by xuqimen** [comment]
Sure, thanks! 

The integral of the total density should be the total number of electrons.

**Comment by bernstei** [comment]
The manual says "no unit" for `EXX_RANGE_FOCK`, which defaults to 0.1587 and says it's the same as VASP.  However, the VASP manual gives values for `HFSCREEN` of 0.2 for HSE06 and 0.3 for HSE03.  From what I can tell this parameter does have units, 1/length, and 0.1587 is equivalent to VASP's 0.3 for HSE03, but that's just based on playing with the values, and this all needs to be specified in the docs.

**Comment by YaphetS-jx** [comment]
Thanks for your feedback! The unit for `EXX_RANGE_FOCK` is `1/Bohr`. I will update the correct units in the docs soon.

**Comment by bernstei** [comment]
Thanks.  It's probably worth documenting that this is "the same as VASP" but only for HSE03, too, since HSE06 uses a different value.
