### ISSUE TITLE
density file atomic positions are wrong

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#127]
The atomic positions in the header of the density files appear to be wrong.  For example, running with this for the `PREFIX.ion` file
```
# Input File Generated By SPARC ASE Calculator #
#CELL:   11.114353808858745   11.154443843030773   11.163719668017823
#LATVEC
# -1.000000000000000  0.000000000000000  0.000000000000000
# -0.000357999044009 -0.999999935918340  0.000000000000000
#  0.491162915337454  0.490426660327026  0.719889353607687
#PBC: True True True 
# 


ATOM_TYPE: Al
N_TYPE_ATOM: 2
PSEUDO_POT: Al.psp8
ATOMIC_MASS: 26.9815385
COORD_FRAC:
     0.377775998824091     0.621032998786236     0.250017999224589   # index 0
     0.622224001078524     0.378967000926453     0.749982000541744   # index 1
RELAX:
1 1 1
1 1 1
SPIN:
 0.600000000000000
 0.600000000000000


ATOM_TYPE: O
N_TYPE_ATOM: 8
PSEUDO_POT: O.psp8
ATOMIC_MASS: 15.999

     0.747417999633703     0.741904999126334     0.497531998910203   # index 10
     0.744494000604332     0.252539000420551     0.998849999656910   # index 11
     0.256920999578256     0.253459999671266     0.003540999022197   # index 12
     0.251977000401936     0.742732000468213     0.498768001015243   # index 13
RELAX:
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
1 1 1
SPIN:
 0.600000000000000
 0.600000000000000
 0.600000000000000
 0.600000000000000
 0.600000000000000
 0.600000000000000
 0.600000000000000
 0.600000000000000


ATOM_TYPE: V
N_TYPE_ATOM: 4
PSEUDO_POT: V.psp8
ATOMIC_MASS: 50.9415
COORD_FRAC:
    -0.000000000000000    -0.000000000000000     0.000000000000000   # index 2
     0.000000000419092     0.000000001279868     0.500000001058860   # index 3
     0.499999999507650    -0.000000000000000     0.000000000000000   # index 4
     0.000000001023168     0.500000001280489     0.500000001058860   # index 5
RELAX:
1 1 1
1 1 1
1 1 1
1 1 1
SPIN:
 5.000000000000000
 5.000000000000000
-5.000000000000000
-5.000000000000000


```
Gives the following density file header
```
Spin-up electron density in Cube format printed by SPARC-X (Print time: Fri Oct 21 13:05:21 2022)
OUTER LOOP: X, MIDDLE LOOP: Y, INNER LOOP: Z.
   14    0.000000     0.000000     0.000000
   45   -0.246986     0.000000     0.000000
   45   -0.000089    -0.247877     0.000000
   45    0.121849     0.121666     0.178592
   13    3.000000    4.198736     6.927278     2.791131
   13    3.000000    6.915618     4.227166     8.372589
    8    6.000000    2.839784     8.337512     0.012838
    8    6.000000    2.807286     2.878906     5.609412
    8    6.000000    8.258843     8.327239    11.124189
    8    6.000000    8.313792     2.869681     5.595614
    8    6.000000    8.307068     8.275538     5.554308
    8    6.000000    8.274570     2.816932    11.150881
    8    6.000000    2.855511     2.827205     0.039531
    8    6.000000    2.800562     8.284762     5.568106
   23   13.000000   -0.000000    -0.000000     0.000000
   23   13.000000    0.000000     0.000000     5.581860
   23   13.000000    5.557177    -0.000000     0.000000
   23   13.000000    0.000000     5.577222     5.581860
.
.
.
```

I'm not sure where these values are coming from, but from what I can tell they are just wrong. When I visualize them they look completely different.  Is there some way to interpret these that makes sense, and I'm just not understanding it, or is there a bug saving positions to the density file?

**Comment by YaphetS-jx** [comment]
Thanks for your feedback. The density file is in cube format. The atomic positions in the header are the Cartesian coordinates while it is fractional coordinates in the ```PREFIX.ion``` file because you are using ```COORD_FRAC``` tag. (For Cartesian coordinates, the tag is ```COORD```) If you convert either of them correctly, then it will be correct.

**Comment by bernstei** [comment]
Can you explain how you think it's possible to convert the lattice coordinates in `PREFIX.ion` so they map to the Cartesian coordinates in the cube file? When I do it I get values consistent with my original `Atoms` object, but not with the values in the cube file.

As far as I can tell, the combination of `CELL` and `LATVEC` give the following cell row vectors
```
[[-1.11143538e+01  0.00000000e+00  0.00000000e+00]
 [-3.97892804e-03 -1.11143531e+01  0.00000000e+00]
 [ 5.45895842e+00  5.45077542e+00  8.00110498e+00]]
```
Using this to scale, e.g., the second V atom's lattice coordinates which are `0.000000000419092     0.000000001279868     0.500000001058860` transforms the them to the Cartesian `[ 2.72947921  2.7253877   4.0005525 ]`.  This value is also consistent with the Cartesian position that was in the `Atoms` object which was passed to the SPARC-X ASE Calculator. 

However, it is nowhere near the value in the cube file `23   13.000000    0.000000     0.000000     5.581860`.  It sort of looks like the positions in the cube file are being generated by multiplying the lattice positions by  the CELL values, but ignoring the directions vectors in LATVEC. 

[note to self: source is VO2_hybrid/job.Al2V4O8]

**Comment by YaphetS-jx** [comment]
Yes, you are right that ```the positions in the cube file are being generated by multiplying the lattice positions by the CELL values, but ignoring the directions vectors in LATVEC```, which is not the Cartesian coordinates. I will fix it in the next release. Thanks for your explanation and advice!

**Comment by YaphetS-jx** [comment]
This is issue is fixed in SPARC version 02/13/2023. Thanks for your feedback!
