### ISSUE TITLE
Memory management for large scale AIMD

### ISSUE THREAD

**Issue by againsmile1** [SPARC-X/SPARC#128]
I tried to run NVT AIMD w/ 170 atoms/cell. It is 
an amorphous structure. SPARC showed me a result initially, but it crashed after around 100 steps. I checked memory consumption during md step and it continuously increases and thus when it is over the physical memory (380GB in my cluster), the calculation is crashed. I tried it with another cluster of which memory is 760GB, but it crashed as well though it is alive a little longer time.
 Are there any specific options to control the memory consumption  during md step? Or, if you have any examples with larger system, please share it as well

**Comment by phanish-suryanarayana** [comment]
The memory consumption should not change with increasing number of MD steps, i.e., the memory required for 1 step should be representative for any number of steps. Could you provide the input, ion, pseudopotential, and .out  file that you are using? We can look into it and identify the source of the issue. This suggests a memory bug, for which it would be good to replicate the exact situation, including the number of processors.

**Comment by againsmile1** [comment]
How can I attach files?

**Comment by phanish-suryanarayana** [comment]
While typing your message here, at the bottom of the box you can see "attach files by dragging and dropping, selecting or pasting them"

**Comment by againsmile1** [comment]
[SiO2.ion.txt](https://github.com/SPARC-X/SPARC/files/9875710/SiO2.ion.txt)
[SiO2.inpt.txt](https://github.com/SPARC-X/SPARC/files/9875711/SiO2.inpt.txt)

Please check input files which I used. I used the same pseudopotetnails in the soruce code, and run it with 96 cores in a single node. I tested smaller number of cores such as 24 cores or 12 cores as well, but the system was crashed, neither. With 96 cores, single MD step needs fewer time, but crashed at around 100 steps. With 24 cores, each MD step needs more time, but crashed at around 300 steps. In both cases, memory consumption gradually increases with MD step, and when the required memory is over the physical memory, the system is crashed.

**Comment by againsmile1** [comment]
[run.out.txt](https://github.com/SPARC-X/SPARC/files/9875807/run.out.txt)
[SiO2.out_04.txt](https://github.com/SPARC-X/SPARC/files/9875808/SiO2.out_04.txt)
 
Attaching two out files.

**Comment by phanish-suryanarayana** [comment]
[SiO2.out.txt](https://github.com/SPARC-X/SPARC/files/9914622/SiO2.out.txt)

As you can see from this output, we were not able to replicate the issue you mentioned, and the code ran without any issues for >700 steps (the simulation stopped due to wall time being exceeded). By the way, I noticed that your ELEC_TEMP is order of magnitude lower than the ION_TEMP. If this was not done on purpose, might be good to set it equal to ION_TEMP. This will significantly speed up calculations, reducing the number of SCF required. Also, choosing a smaller time step might be appropriate here.

**Comment by againsmile1** [comment]
Thank you for your efforts.
Could you let me know how many nodes are used and physical memories of your
system?

During the calculation, I checked "VIRT", "RES' of each nodes. It starts
below hundreds MB, but continuously increased after several hundreds step.

Depending on the system, the calculations may not be stopped during the
several hundreds steps. But, if you can see the changes, especially,
increase of "RES", I'm sure the system will be crashed.

Please check the "RES" of your system.

Regards,

Sunghoon



2022년 11월 2일 (수) 오전 8:28, phanish-suryanarayana ***@***.***>님이
작성:

**Comment by againsmile1** [comment]
I have one more question.

Could you let me know details of the build environment?

1. Version of intel compiler
2. Kinds of mpi and version
3. Usage of  Non-mkl blas, lapack, scalapack fftw

If you give those information, I will try to recompile it.

Best regards,

Sunghoon

2022년 11월 3일 (목) 오후 12:30, Sunghoon Lee ***@***.***>님이 작성:

**Comment by phanish-suryanarayana** [comment]
Many thanks for following up. @StevenZhangCSFM is looking into the possible issue and why we didn't encounter it. We will get back to you soon.

**Comment by StevenZhangCSFM** [comment]
@againsmile1 Hi Sunghoon,
I made another test using 96 processors and 380GB memory to run the MD for 70 steps, and used massif tool in valgrind to record the memory usage of every processor at about 100 snapshots in the simulation.
The record from massif shows that there was no tendency of increasing memory usage with the continuing NVT simulation.
The modules used in this test were: gcc8.3.0, mvapich2.3.2, mkl19.0.5 and valgrind3.16.1.
![memory](https://user-images.githubusercontent.com/65296756/203834301-1cf879b8-a326-4156-be8b-f00717151cd3.PNG)

**Comment by againsmile1** [comment]
Hi Boqin,

Thank you for your efforts on this issue.
I tested with your modules in my machine, and it solved!

The difference with your modules and mine are mvapich and intel mpi. I
compiled again with yours, and it is prefectly working now. The memory
consumption is very stable and doesn't change. I think I can use the same
setting for my work. Thanks a lot!

I appreciate your time and effrot again.

Best regards,

Sunghoon





2022년 11월 25일 (금) 오전 1:49, Boqin Zhang ***@***.***>님이 작성:
