### ISSUE TITLE
printing out wavefunctions

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#130]
We're trying to understand why we're getting states in the gap, and it would be helpful to get some sort of spatially and energy resolved information. One option, probably the simplest to code, would be if SPARC could save the wavefunctions (perhaps only in a specified energy or state # range).  Another, which would require more parameters inside SPARC but perhaps less I/O, would be to save an atom-projected density of states.

**Comment by ajmedford** [comment]
We have done something similar in the past (see Fig. 6 of https://pubs.acs.org/doi/pdf/10.1021/acs.jpcc.1c08915), but I think we did this with some development code. @YaphetS-jx was working on re-formatting I/O so there might be something more official now. If not, then perhaps @ssahoo41 can point you to the version of the code she used when writing the paper.

**Comment by bernstei** [comment]
Is this addressed by `PRINT_ORBITAL`, which I just missed somehow?

**Comment by bernstei** [comment]
If so, it would still be very help to control which orbitals get printed, since the system is big and I don't necessarily want hundreds of them.

**Comment by ssahoo41** [comment]
Yes, it is addressed by `PRINT_ORBITAL`. The SPARC documentation has instructions on how to control which orbitals get printed.

**Comment by YaphetS-jx** [comment]
Some details of PRINT_ORBITAL option is missing in the doc. You can print only part of the wavefunctions by adding 6 additional parameters determining the range of wavefunctions you want to print after `PRINT_ORBITAL: 1`, and those parameters are index for spin_start, spin_end kpt_start kpt_end band_start band_end. Start index start from 0 and end index are inclusive. 

For example, you want to print wavefunctions for spin index 0, kpt index 0 and 1, band index from 1 to 3, then the option you will use is `PRINT_ORBITAL: 1 0 0 0 1 1 3`
