### ISSUE TITLE
What is "WARNING: The density after mixing has negative components!" 

### ISSUE THREAD

**Issue by Jiang-eat-sugar** [SPARC-X/SPARC#176]
Hi, 

Does anyone know what causes the error "WARNING: The density after mixing has negative components!" and how to fix it?  

Thanks,
Jiang

**Comment by Jiang-eat-sugar** [comment]
Some of the calculations happened in the middle and then disappeared in the end. Some showed up at the very end. I am calculating a crystal structure. 

I am sharing the files here:
https://drive.google.com/drive/folders/1seazVtDFypRixWbmlLPlK9LORwJVqgcV?usp=sharing

**Comment by StevenZhangCSFM** [comment]
Hi Jiang,
Could you let me know that which pseudopotentials you used? Is it from /psps/ folder in SPARC? Is there any modification on these pseudopotentials?

**Comment by Jiang-eat-sugar** [comment]
Right, the pseudopotentials that I used are from /psps/ folder in SPARC. Actually, I am wondering how those pseudopotentials compare with the pseudopotentials in vasp. I just used EXCHANGE_CORRELATION: GGA_PBE. 

Below is the Google Drive folder that contains the makefile:
https://drive.google.com/file/d/15Bh8bRHPHN3eoRbCA7p_QeAzntG_AXjO/view?usp=sharing

I downloaded the package from the GitHub website that was updated on Feb 07, 2023 (Name: Xin Jing), based on the ChangeLog.

**Comment by StevenZhangCSFM** [comment]
Hi Jiang,
I set the similar input parameters from your .out file and your .ion file to run the relaxation with v Feb 07 SPARC using 48 processors. However, I did not find the warning message in the output files and log files. The test stopped when the time used up. The module I used to compile is intel/20.0.4 and mvapich2/2.3.6.
Also, I found that the output result in your test at the first SCF step is different from mine. Maybe there is some discrepancy between the input in your test and the files you shared with us. All inputs and outputs are shared in the attached folder.
[BTS.zip](https://github.com/SPARC-X/SPARC/files/11362334/BTS.zip)

**Comment by Jiang-eat-sugar** [comment]
Hi Boqin,

I am not sure why there is discrepancy between our results. I am recalculating the files that you shared with me. At the same time, could you test one more example that I have encountered “The density after mixing has negative components!”?

Below is the Google folder having the new example:
https://drive.google.com/drive/folders/1B0T9xSvxXNG-Goceno1NFew2DwD4k3oR?usp=sharing

Thanks,
Jiang

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by StevenZhangCSFM** [comment]
Hi Jiang,
I tried using another set of modules, mkl/20.0.4, netlib-scalapack/2.2.0, mvapich/2.3.6 to run the BTS test again. The result is attached to the mail, which is similar to my previous result, and still different from the test result you sent to us. Also, I did not see the warning message in this test either.
It seems that I do not have permission to open you new example. I cannot access to it.
[BTS2.zip](https://github.com/SPARC-X/SPARC/files/11362769/BTS2.zip)

**Comment by Jiang-eat-sugar** [comment]
https://drive.google.com/drive/folders/1B0T9xSvxXNG-Goceno1NFew2DwD4k3oR?usp=sharing
I opened the access of the new folder.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Boqin ***@***.***>
发送时间: Sunday, April 30, 2023 7:28 PM
收件人: ***@***.***>
抄送: Luo, ***@***.***>; ***@***.***>
主题: Re: [SPARC-X/SPARC] What is "WARNING: The density after mixing has negative components!" (Issue #176)


Hi Jiang,
I tried using another set of modules, mkl/20.0.4, netlib-scalapack/2.2.0, mvapich/2.3.6 to run the BTS test again. The result is attached to the mail, which is similar to my previous result, and still different from the test result you sent to us. Also, I did not see the warning message in this test either.
It seems that I do not have permission to open you new example. I cannot access to it.
BTS2.zip<https://github.com/SPARC-X/SPARC/files/11362769/BTS2.zip>

―

**Comment by StevenZhangCSFM** [comment]
Hi Jiang,
I ran the new system that you shared with me. The good thing is that now the results from my test fit your output file.
To save the running time, I set a limit on relaxation iteration time. Now I have seen the warning. You can see from my output files, however, the job can run with these warnings. I think you can just keep it on.
My inputs and outputs are attached to here.
[BTS3.zip](https://github.com/SPARC-X/SPARC/files/11363379/BTS3.zip)
