### ISSUE TITLE
What is the preferred K-point grid? 

### ISSUE THREAD

**Issue by Jiang-eat-sugar** [SPARC-X/SPARC#177]
Hi,

I tried to use a similar rule of thumb for the K-point grid in vasp calculation (a*k=30). It greatly increased the cost of the computation resources. Then, I saw K-point grid is 2 * 2 * 2 in the testing example "AlSi_primitive_quick_relax" with a cell size of 7 * 7 * 7. Does anyone know if there is a rule of thumb for the K-point grid in sparc-X calculation? 

Thanks,
Jiang

**Comment by phanish-suryanarayana** [comment]
The k-point grid in all DFT codes works in the same way. In other words, the number of k-points required should not change between DFT codes for the same choice of smearing. Note that SPARC does not do symmetry reduction in k-points, so the increase in cost might appear substantial.
