### ISSUE TITLE
The energy of crystal structure from RELAX_FLAG: 2/1 is lower than that from RELAX_FLAG: 3

### ISSUE THREAD

**Issue by Jiang-eat-sugar** [SPARC-X/SPARC#178]
Hi,

I  obtained a relaxed BaTiS3 structure with RELAX_FLAG: 2 first, and then with RELAX_FLAG: 1. This relaxed BaTiS3 structure with RELAX_FLAG: 2 and RELAX_FLAG: 1 has lower energy than the relaxed BaTiS3 structure with RELAX_FLAG: 3. In both cases, I used the same convergence setting. It seems like the "RELAX_FLAG: 3" setting missed a local minimum structure. Does anyone know what is a reliable way to get a fully optimized structure?

**Comment by Jiang-eat-sugar** [comment]
Also, the method with "RELAX_FLAG: 3" takes much longer time than the method with RELAX_FLAG: 2 first and then RELAX_FLAG: 1.

**Comment by phanish-suryanarayana** [comment]
Yes, using RELAX_FLAG: 3 can be tricky. In your particular example, might be easier to do 1 and 2, possibly in a loop.
