### ISSUE TITLE
Help with extracting band gap and band structure 

### ISSUE THREAD

**Issue by Jiang-eat-sugar** [SPARC-X/SPARC#189]
Good morning, 

I want to extract the band gap information from the results of sparc static calculation. I assume the density of state(DOS) is from the .eigen file. What is the unit in the "eigval" column? Is it Hartree? In addition, if I want to plot band structure, which file should I look for?

Thanks,
Jiang

**Comment by ajmedford** [comment]
At the moment, we don't have formal infrastructure for plotting DOS, but it is something we have done before. The units should be in Hartree. @ssahoo41 - can you provide the scripts you used for this? We should also think about incorporating this analysis into the Python API to make it easier to use.

**Comment by xuqimen** [comment]
The eigenvalues are in Hartree as @ajmedford mentioned. Regarding the band structure, we've been working on adding this feature recently and we will provide a Python script to extract the result and/or to create a plot. This feature should be ready in a few days.

**Comment by ssahoo41** [comment]
I used the attached script to plot the DOS using the eigenvalues from .eigen script. 
[DOS_script.zip](https://github.com/SPARC-X/SPARC/files/12223510/DOS_script.zip)

**Comment by Jiang-eat-sugar** [comment]
Thanks for letting me know the unit in the .eigen file and sharing the code to plot DOS. I am looking forward to seeing the feature of plotting band structure.

**Comment by xuqimen** [comment]
The band structure calculation feature is now available in SPARC. You can enable band structure calculations by setting `BAND_STRUCTURE: 1` in the `.inpt` file. Additionally, you'll need to configure `KPT_PATHS`, `KPT_PER_LINE`, and `INPUT_DENS_FILE` accordingly (for more details, refer to the [Manual](https://github.com/SPARC-X/SPARC/blob/master/doc/Manual.pdf)). An example can be found in the `tests/CdS_bandstruct/` directory.

Furthermore, we've provided a Python script in the `utils/bandstruct/` directory to process the results and visualize the band structure.

**Comment by Jiang-eat-sugar** [comment]
That is great! I will test the band structure feature soon. By the way, is the phonon band structure feature available now?

**Comment by xuqimen** [comment]
Great! Phonon band structure calculations have not been implemented yet.

**Comment by xuqimen** [comment]
Did you run the same test as the one in the `tests/CdS_bandstructure/standard` directory? We need a bit more information to identify the source of the issue. Could you please try rerunning your test in debug mode by setting `DEBUG_MODE = 1` in the makefile and recompiling the code using `make clean; make -j8`.

**Comment by xuqimen** [comment]
@Jiang-eat-sugar Just a reminder that your job script tries to run the test with 64 processes (`srun -n 64`) while the number of tasks requested is `48` (`#SBATCH -n 48`). When you get a chance to rerun the test in debug mode, it's best to fix this discrepancy.
