### ISSUE TITLE
compiling with MKL fails to find lapacke.h

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#23]
I set USE_MKL=1, USE_SCALAPACK=0, and USE_DP_SUBEIG=1.  When I compile, I get the following error
```
mpicc -std=gnu99 -O3 -fopenmp -Iinclude/ -DUSE_DP_SUBEIG  -c -o orbitalElecDensInit.o orbitalElecDensInit.c
orbitalElecDensInit.c:20:14: fatal error: lapacke.h: No such file or directory
     #include <lapacke.h>
              ^~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: orbitalElecDensInit.o] Error 1
```

Is there a dependence on something other than plain LAPACK? My MKL installation (2020.2.254) doesn't seem to have this file, and even if it did there's no attempt to add its include/ path to the compile line.

**Comment by huanghua1994** [comment]
Hi bernstei,

According to your compiling log, can you please try replacing line 37 in `src/makefile`

```make
ifeq ($(USE_MKL), 1)
```

with 

```make
ifeq ($(strip $(USE_MKL)), 1)
```

and see if it works?

**Comment by bernstei** [comment]
That works, but the original worked too.  I was making a mistake, and was not modifying the actual "makefile", but a separate renamed copy.  Sorry about the false alarm.  Feel free to close.
