### ISSUE TITLE
multi-projector PPs

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#24]
John Pask advertised SPARC-X as being able to use the new multi-projector PP formalism, which I gather is supported by v 4 of Don Hamann's [code](http://www.mat-simresearch.com/).  Is this true, and if so, is there a database of such PPs anywhere?

**Comment by xuqimen** [comment]
Hi bernstei,

Yes, it's true. You can check [this page](https://github.com/xuqimen/SG15_pseudopotentials_psp8_upf) for a set of [SG15 pseudopotentials](http://www.quantum-simulation.org/potentials/sg15_oncv/) in psp8 format regenerated using Hamann's ONCVPSP-4.0.1 code. These can be used for SPARC.

Qimen

**Comment by bernstei** [comment]
Thanks. Are these the original SG15 just regenerated with the newest code?  Or are they a new set with more projectors for additional accuracy?

**Comment by xuqimen** [comment]
These are just regenerated with the same input but converted to psp8 format using the newest (beta) code.

**Comment by phanish-suryanarayana** [comment]
In the near future (a month or so), we will be providing a set of multi-projector ONCV pseudopotentials, which should be transferable and as soft as possible. Apart from the SG15 pseudopotentials, there is a much larger set of pseudopotentials available at: http://www.pseudo-dojo.org . Though this released version is not compatible with these pseudopotentials, the development version is, so we can make that available in case you are interested. 

P.S. I guess this is Noam, based on the question you asked during John Pask's talk.

**Comment by bernstei** [comment]
I just checked out pseudo-dojo, and the first PP I downloaded gives the error
```
fchrg = 3.50000000 > 0.0 (icmod != 0)
This pseudopotential contains non-linear core correction. 
It is not supported by current version! Exiting ...
```

Is there a particular set on there that is known to be compatible with SPARC?

**Comment by phanish-suryanarayana** [comment]
None from the pseudoDOJO site. However, NLCC has already been implemented in SPARC a while ago, and that version will be merged with master in the next few days.

**Comment by phanish-suryanarayana** [comment]
All pseudopotentials from the pseudoDOJO site and ONCV pseudopotentials with NLCC in general, can now be used in SPARC.

**Comment by xuqimen** [comment]
Just a reminder that pseudoDOJO pseudopotentials use "D" instead of "E" for scientific notation. Since C language doesn't support this by default, you would have to replace all "D+" with "E+" and all "D-" with "E-". If you're in Linux, you can do this by the following commands:
 `sed -i "s/D+/E+/g" *.psp8`
 `sed -i "s/D-/E-/g" *.psp8`
