### ISSUE TITLE
documenting makefile, in particular libraries that will be used

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#25]
It would be nice if there was a bit more documentation on the libraries that will be used, and a cleaner way of specifying them. In particular, I was getting weird crashes until I noticed that it was using MKL scalapack and MKL blacs for intelmpi. I had to change it to the openmpi version, but it would be better if this was at least documented, especially since the current description of USE_DP_SUBEIG makes one think it won't use scalapack at all if that's set.

**Comment by xuqimen** [comment]
Hi bernstei,

Thanks for the suggestions! I'm not an expert on makefiles, so I don't know what's the best way to prevent the conflict of libraries, but we'll see what we can do to make it more clear. 

`USE_DP_SUBEIG` is only to replace the `pdgemm/pzgemm` calls (and the corresponding data distribution routine for block-cyclic data format) with our own routines, other scalapack routines such as dense parallel eigensolver might still be used if your system is large. When both `USE_MKL` and `USE_SCALAPACK` are turned off (option 1 of the installation guides), then no scalapack functions will be use at all.

Qimen
