### ISSUE TITLE
Memory requirement much larger than it should be

### ISSUE THREAD

**Issue by phanish-suryanarayana** [SPARC-X/SPARC#26]
The memory requirement is much larger than it should be. Many thanks to Noam Bernstein for bringing this to our attention!

**Comment by bernstei** [comment]
@phanish-suryanarayana What's the status of this issue?  I'm trying to do direct comparisons with another code, and the memory usage situation is pretty problematic.  The PW code I'm comparing to is using a cutoff of 400 eV (40/80 G-vectors/direction for wf/density), 35 irreducible k-points, and it's about 60 MB per process (72 cores).  SPARC (commit 8758f15c1) with an ECUT of 900 eV =~ 33 Ha, gets a corresponding FD mesh of 43^3, here I use 5^3 k-point mesh (I don't know exactly how many are left after time reversal symmetry, but say around 70), and it's using 2 GB per process (also 72 cores).  

The basis is of comparable size, twice as many k-points, but it's apparently using 30x more memory.

**Comment by bernstei** [comment]
I guess one thing I forgot to check the number of electrons, but that's 232 for the PW code, 264 for SPARC, so not a big difference.

**Comment by phanish-suryanarayana** [comment]
Thanks for reminding us. This issue had fallen through the cracks, since we were focused on a number of other major developments. It should be fixed in the next few days!

**Comment by phanish-suryanarayana** [comment]
Fixed!
