### ISSUE TITLE
README information on tests is out of sync

### ISSUE THREAD

**Issue by bernstei** [SPARC-X/SPARC#42]
The README file refers to a `quickrun.sh` script which does not seem to exist.  It would be nice to update it to whatever the latest way of doing testing actually is.

**Comment by xuqimen** [comment]
@shashikant193 has been working on a new automatic testing framework and the previous tests/ folder was removed at some point. We'll create a new `quickrun.sh` to be consistent with the README file. We'll also add some information about the new testing framework in the README. Thanks for pointing out this issue!

**Comment by phanish-suryanarayana** [comment]
Fixed!
