### ISSUE TITLE
Error in running simulations on Brown University Cluster

### ISSUE THREAD

**Issue by mayank-agr** [SPARC-X/SPARC#57]
Hi

I am trying to run single point energy calculation for my system (contains Pt, C, H, O and total of 221 atoms) on my cluster at Brown university. However, I am getting the following error. Please note that Jagriti was able to run the same calculation successfully on PACE cluster at Georgia Tech. 

The error is:
  1 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  2 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  3 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  4 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  5 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  6 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  7 INTERNAL ERROR: invalid error code 66 (Ring ids do not match) in MPIR_Alltoallv_intra_scattered:124
  8 Fatal error in PMPI_Alltoallv: Unknown error class, error stack:
  9 PMPI_Alltoallv(361)................: MPI_Alltoallv(sbuf=0x7fe598adc010, scnts=0x1cc0710, sdispls=0x1c    c0740, dtype=0x4c001041, rbuf=0x7fe5c8484010, rcnts=0x1cc0770, rdispls=0x1ce2da0, dtype=0x4c001041, c    omm=0xc400000f) failed
 10 MPIR_Alltoallv(193)................:
 11 MPIR_Alltoallv_intra(105)..........: Failure during collective
 12 MPIR_Alltoallv_intra(100)..........:
 13 MPIR_Alltoallv_intra_scattered(124):
 14 MPID_nem_tcp_connpoll(1845)........: Communication error with rank 47: Connection timed out
 15 MPIR_Alltoallv_intra_scattered(124):
 16 MPIR_Alltoallv_intra_scattered(124):
 17 MPIR_Alltoallv_intra_scattered(124):
 18 MPIR_Alltoallv_intra_scattered(124):
 19 MPIR_Alltoallv_intra_scattered(124):
 20 MPIR_Alltoallv_intra_scattered(124):
 21 MPIR_Alltoallv_intra_scattered(124)

I will highly appreciate any help to debug this problem. @xuqimen

Thanks,
Mayank

**Comment by xuqimen** [comment]
@mayank-agr Were you able to run any other tests in SPARC? For example, the tests described in README?

For this particular test, what options did you use to compile the code (USE_MKL, USE_SCALAPACK, USE_DP_SUBEIG)? Could you share the log file (or messages printed on-screen) you got when running this test in DEBUG mode?

Regards,
Qimen

**Comment by mayank-agr** [comment]
Hi Qimen,

Yes, I was able to run all the tests successfully. For my installation, I used USE_MKL=1. I am attaching the log file and out files here. I shared the error in the error file above. Please let me know if there is anything else you need. 

Thanks
Mayank
[in1_out.txt](https://github.com/SPARC-X/SPARC/files/7125245/in1_out.txt)
[slurm-2383978.txt](https://github.com/SPARC-X/SPARC/files/7125246/slurm-2383978.txt)

**Comment by xuqimen** [comment]
@mayank-agr Could you try setting `USE_DP_SUBEIG = 0` and re-compile the code? MPI_Alltoallv is most likely being called in the DP routines, which can be replaced using MKL routines.

Regards,
Qimen

**Comment by mayank-agr** [comment]
Hi Qimen,

I am getting the following error after recompiling the way you suggested. I was able to run the tests successfully in this case as well. 
(USE_MKL=1, USE_SCALAPACK=0, USE_DP_SUBEIG = 0)

  **1 Fatal error in MPI_Recv: Unknown error class, error stack:
  2 MPI_Recv(200).........................: MPI_Recv(buf=0x7f823babd080, count=2785050, dtype=USER<contig    >, src=6, tag=9, comm=0xc400000c, status=0x7ffe77463550) failed
  3 MPIDU_Complete_posted_with_error(1137): Process failed**


The modules available on my cluster are:
java/8u111                   gcc/10.2
matlab/R2017b                intel/2020.2
python/3.9.0                 scalapack/2.0.2
mpi/mpich3.3a3_intel_2020.2

Hope it will be of help to debug the issue. 

Thanks,
Mayank

**Comment by xuqimen** [comment]
@mayank-agr Are you able to run SPARC on multiple nodes for those simple tests in SPARC? I suspect there's some issue with MPI on multiple nodes. 

If it fails, could you try the [standalone test](https://github.com/xuqimen/pdsygvd) you tried before on multiple nodes as well? E.g., 
```
mpirun -np 72 ./test_eig 1000 8 9
```

Regards,
Qimen

**Comment by mayank-agr** [comment]
@xuqimen I ran a calculations on multiple nodes in the Example_tests using the following command and it successfully ran.
**mpirun -np 48 sparc -name Si8_kpt**

And for the mpirun -np 72 ./test_eig 1000 8 9, it is running as follows (it is slow):
**(sparc-venv) (conda_py3.6) [magrawa3@login006 pdsygvd]$ mpirun -np 72 ./test_eig 1000 8 9**

**********************************
*        Process Grid Info       *
**********************************
Number of processes:   72
2-D Process grid dims:   8 x   9
Matrix size: 1000 x 1000
Local Matrix size: 128 x 128
Start calculation ...

Start matrix multiplication ...

Multiplying matrix took 4704.347 ms
rank = 0, abstol = 2.225e-308, calculating abstol (for most orthogonal eigenvectors) took 170.949 ms
rank = 0, info = 0, work(1) = 43576.000000, iwork(1) = 6000, time for workspace inquery: 294.203 ms
rank = 0, info = 0, time for QR eigensolver: 325999.010 ms
rank = 0, info = 0, time for pdsygvd (D&C eigensolver): 347272.735 ms
err in eigvals (pdsygvd, D&C): 5.821e-11
err in eigvecs (pdsygvd, D&C): 5.223e-12

Hope it helps
Thanks,
Mayank

**Comment by xuqimen** [comment]
Hi Mayank,

Well, at least the code runs. Although when I ran the standalone test on the cluster at GT, it was much faster than your result:
```
**********************************
*        Process Grid Info       *
**********************************
Number of processes:   72
2-D Process grid dims:   8 x   9
Matrix size: 1000 x 1000
Local Matrix size: 128 x 128
Start calculation ...

Start matrix multiplication ...

Multiplying matrix took 240.634 ms
rank = 0, abstol = 2.225e-308, calculating abstol (for most orthogonal eigenvectors) took 0.078 ms
rank = 0, info = 0, work(1) = 43576.000000, iwork(1) = 6000, time for workspace inquery: 33.615 ms
rank = 0, info = 0, time for QR eigensolver: 854.739 ms
rank = 0, info = 0, time for pdsygvd (D&C eigensolver): 389.945 ms
err in eigvals (pdsygvd, D&C): 1.164e-10
err in eigvecs (pdsygvd, D&C): 5.604e-10
rank = 0, info = 0, time for pdsygv (non-expert QR eigensolver): 337.727 ms
err in eigvals (pdsygv, non-expert QR): 5.821e-11
err in eigvecs (pdsygv, non-expert QR): 8.727e-13
```

Since the matrices are generated randomly in the standalone test, the error value might not be the same, but the cost should be similar. I think there is some issue with the multi-node runs.

Did you observe a similar slow-down of SPARC on multiple nodes for the simple test?

Regards,
Qimen

**Comment by mayank-agr** [comment]
Hi Qimen,

I believe even small tests (e.g. Si8_kpt in Example folder) are pretty slow on multiple nodes. They should get finished almost instantly but this one is taking more than a couple of minutes for sure. 

Also for the simple python test.py quick_run, it took around 15 seconds to finish. I feel this is slow as well. Hope we figure out the problem soon. 

Thanks for your continuous help,
Mayank

**Comment by xuqimen** [comment]
@mayank-agr I think the MPI issue is more related to your MPI/hardware. The best way would be to contact your cluster support regarding the multiple-node issue. It might be related to the affinity setting of MPICH. I suggest you use the standalone test for debugging the issue since it's an independent MPI+MKL example outside SPARC. 

In the meanwhile, we'll also think about how we can better pinpoint the issue within SPARC.

Regards,
Qimen

**Comment by mayank-agr** [comment]
Hi Qimen,

Thanks for your support. I have already emailed the cluster support and waiting for their reply. 

One thing I wanted to point out here is whether or not it is possible to update SPARC code in a way that it can work on different MPIs. Out of 12 MPIs I have on my cluster, I was able to run SPARC only on one MPI. Other options of openmpi etc didn't work for installation. 

I will keep you updated after debugging the issue with cluster support.

Thanks a lot for your help. 

Best,
Mayank

**Comment by xuqimen** [comment]
@mayank-agr You're welcome, let's see if they have a solution for the multiple-node issue.

As for making SPARC compatible with different MPI, since you mentioned in this issue (#56) you couldn't run the standalone MKL example test using the other 11 MPI versions on your cluster. I think it's most likely related to the MKL installation/linkage on your cluster. You might try the [suggestion](https://github.com/SPARC-X/SPARC/issues/56#issuecomment-906084269) I brought up regarding the linking advisor for MKL with different MPI.

Regards,
Qimen
